### ISSUE TITLE
Breaks debugger on RN 0.22+

### ISSUE THREAD

**Issue by arjun-io** [feathersjs/feathers-react-native-chat#11]
@ekryski I know you know about this already (https://medium.com/@ekryski/how-to-actually-use-socket-io-in-react-native-39082d8d6172#.ki8h092bk) but I thought it might be useful for others to have here as well.

I was scratching my head as to why my app was breaking after upgrading to RN 0.22, you will end up getting an error like:
`Cannot set property navigator of [object Object] which has only a getter` when you debug in Chrome.

A temporary workaround is to comment out the line

`window = Object.assign(window, { navigator: { userAgent: 'ReactNative' } });`

in your code, and in your Chrome debugger console run

`window.navigator.userAgent = 'ReactNative'`

This will only work while you're debugging, so when you stop debugging in Chrome, you'll have to uncomment the line.

**Comment by lopezjurip** [comment]
I'm using RN 0.22 and have it working using `jsonp: false` on socket settings:

``` js
import io from 'socket.io-client/socket.io';

if (window.navigator && Object.keys(window.navigator).length === 0) {
  window = Object.assign(window, { navigator: { userAgent: 'ReactNative' } });
}

const host = 'http://localhost:3030';
const socket = io(host, {
  transport: ['websockets'],
  jsonp: false,
});
```

**Comment by ekryski** [comment]
@mrpatiwi good to know! Thanks! Socket.io is kind of weird in that I don't think it really respects the `transports` array.

On another note, the proper fix for socket.io just got merged https://github.com/socketio/engine.io-parser/pull/55. So once the release is out we won't need this hack at all :smile:

**Comment by ekryski** [comment]
Apparently an engine.io release is going out tomorrow. Will verify and then this should be closed afterwards.
