### ISSUE TITLE
error installing features-authentication

### ISSUE THREAD

**Issue by shahraship** [feathersjs/feathers-react-native-chat#12]
$ npm install feathers-authentication

> bcrypt@0.8.7 install /Users/user/Developer/tests/feathers-react-native-chat/node_modules/bcrypt
> node-gyp rebuild

2016-08-16 07:47:07.979 xcodebuild[50415:30055117] Build settings from command line:
2016-08-16 07:47:07.979 xcodebuild[50415:30055117]     TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
2016-08-16 07:47:07.980 xcodebuild[50415:30055117]     XCODE_DEFAULT_TOOLCHAIN_OVERRIDE = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [Release/bcrypt_lib.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/Cellar/node/5.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Developer/tests/feathers-react-native-chat/node_modules/bcrypt
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
feathersreactnativechat@0.1.0 /Users/user/Developer/tests/feathers-react-native-chat
└─┬ react-native@0.21.0
  └─┬ ws@0.8.1
    └── bufferutil@1.2.1 

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/5.6.0/bin/node" "/usr/local/bin/npm" "install" "feathers-authentication"
npm ERR! node v5.6.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Developer/tests/feathers-react-native-chat/npm-debug.log

**Comment by daffl** [comment]
The dependency needs to be updated to `^0.7.0`. I think there wasn't any API changes so it might work just changing it.

**Comment by corymsmith** [comment]
This has been updated to use feathers-authentication-client so this is no longer an issue
