### ISSUE TITLE
Decorators are "unexpected tokens"

### ISSUE THREAD

**Issue by Pampounet** [feathersjs/feathers-react-native-chat#15]
While I try to run iOS version, I get this error : 
![simulator screen shot 10 avr 2017 a 19 09 59](https://cloud.githubusercontent.com/assets/25985310/24873521/666bb55a-1e21-11e7-8796-7454ccd4434a.png)

This refers to `@autobind @observer` in Application.js
I tried to add a `.babelrc` file containing `{ "plugins": ["babel-plugin-transform-decorators-legacy"] }` but it does not work... Is this a problem with my configuration ?
I really want to test it, to better understand Feathers running...

Thanks !

**Comment by corymsmith** [comment]
Are you running this app or another app with some of this code?

**Comment by corymsmith** [comment]
You need at least this: https://github.com/feathersjs/feathers-react-native-chat/blob/master/.babelrc#L7 and https://github.com/feathersjs/feathers-react-native-chat/blob/master/package.json#L29

**Comment by Pampounet** [comment]
@corymsmith I'm running the exact same repo on GitHub, without any modifications ! 
Okay I try your suggestions :)

**Comment by corymsmith** [comment]
And you ran `npm install`?

**Comment by Pampounet** [comment]
I have checked everything again (to see if the files were there as foreseen), and it's the exact copy of the repo.

Yes, i have run `npm install`...

**Comment by Pampounet** [comment]
My bad, I was doing mistakes with my terminal... Very sorry for the inconvenience !

By the way, Feathersjs is amazing and I really congratulate all of you 👍

**Comment by Harrisandwich** [comment]
@Pampounet What did you do wrong in the terminal. I'm encountering a similar issue and I can't find the answer I need

**Comment by why06** [comment]
If anyone is having this issue, you may need to restart metro bundler. Seems kinda obvious now, but it took me way too long to figure out.
