### ISSUE TITLE
compilation fail

### ISSUE THREAD

**Issue by ramsestom** [feathersjs/feathers-react-native-chat#16]
Here is the error I get when trying to compile feathers-react-native-chat for android:

Objects are not valid as a React child (found: object with keys {visible}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `View`.

**Comment by maxprog** [comment]
Hi, I have exactly 
<img width="543" alt="screen shot 2017-05-05 at 19 38 03" src="https://cloud.githubusercontent.com/assets/13249768/25757358/687e247e-31ca-11e7-9bdc-f8fab416b379.png">
the same error - problem is in Application.js and related with related with 


         {this.store.isAuthenticated ? <MainNavigator screenProps={{store: this.store}}/> :
          <UnauthenticatedNavigator screenProps={{store: this.store}}/>}
  
StackNavigator Objects MainNavigator and UnauthenticatedNavigator are placed in render () function. If we place modules without StackNavigator - then works - I suppose that StackNavigator is used in wrong way

**Comment by maxprog** [comment]
sorry, I don't know why github cut snippet of source code:  
render() {
    return (
     
   <View style={{flex: 1}}>
         {this.store.isAuthenticated ? <MainNavigator screenProps={{store: this.store}}/> :
          <UnauthenticatedNavigator screenProps={{store: this.store}}/>}
             </View>
   
    );
  }

**Comment by corymsmith** [comment]
It looks like they made some breaking changes to `react-navigation` which is whats causing these errors. I'll have to fix
