### ISSUE TITLE
Error during run android or IOS 

### ISSUE THREAD

**Issue by maxprog** [feathersjs/feathers-react-native-chat#18]
Hi,
I have error during run android version:
The SDK Build Tools revision (23.0.1) is too low for project ':react-native-vector-icons'. Minimum required is 25.0.0
<img width="1125" alt="screen shot 2017-05-10 at 08 40 01" src="https://cloud.githubusercontent.com/assets/13249768/25886090/51d8be6a-355c-11e7-8527-eee46847f4db.png">

and on IOS:
<img width="1120" alt="screen shot 2017-05-10 at 08 41 27" src="https://cloud.githubusercontent.com/assets/13249768/25886133/7e12d074-355c-11e7-9b5e-d265cfd38cb6.png">

**Comment by gianpaj** [comment]
try the last 2 instructions here https://github.com/tomasz-szymanek/react-native/blob/1cc5a1663e6c947c5459a77ae6242822f59f8524/docs/Troubleshooting.md#react-native-cant-find-android_home
