### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by PManager1** [feathersjs/feathers-react-native-chat#21]
when i try to install it - it gives me this error.

Installing build/Build/Products/Debug-iphonesimulator/FeathersReactNativeChat.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/FeathersReactNativeChat.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by corymsmith** [comment]
I renamed the scheme so this should be fixed
