### ISSUE TITLE
No events being fired

### ISSUE THREAD

**Issue by shauncodal** [feathersjs/feathers-react-native-chat#24]
I cannot get the on "create" listener to fire, at all.  I have hooked it up to mongodb and the messages are being saved correctly.

here is the log from feathers server

 @feathersjs/socket-commons Got legacy method call 'message::create' +6s
  @feathersjs/socket-commons Running method 'create' on service 'message' { provider: 'socketio',
  payload: { userId: '5a2f44c39ebbb53e14c6ba40' },
  user: 
   { _id: 5a2f44c39ebbb53e14c6ba40,
     email: 'shaun@codal.co.za',
     password: '$2a$12$tTMGlL3S4P07.fwTvTkpJ.Oq4X38BOSG8UVd4NbUkYewji5i2CCMW' },
  accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJ1c2VySWQiOiI1YTJmNDRjMzllYmJiNTNlMTRjNmJhNDAiLCJpYXQiOjE1MTMwNjM2MDksImV4cCI6MTUxMzE1MDAwOSwiYXVkIjoiaHR0cDovLzE3OC42Mi4xMTAuMTAzIiwiaXNzIjoiZmVhdGhlcnMiLCJzdWIiOiJhbm9ueW1vdXMiLCJqdGkiOiI2NDliNjQ3Ni03YWZiLTQ1ZWEtYjVmNC01OWQwYjZlNDJlMDIifQ.ykQeL_Q3vlu8ftUVdxdT-d1hmFKc0zMQ7FGXJixib4Y',
  headers: 
   { Authorization: 'eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJ1c2VySWQiOiI1YTJmNDRjMzllYmJiNTNlMTRjNmJhNDAiLCJpYXQiOjE1MTMwNjM2MDksImV4cCI6MTUxMzE1MDAwOSwiYXVkIjoiaHR0cDovLzE3OC42Mi4xMTAuMTAzIiwiaXNzIjoiZmVhdGhlcnMiLCJzdWIiOiJhbm9ueW1vdXMiLCJqdGkiOiI2NDliNjQ3Ni03YWZiLTQ1ZWEtYjVmNC01OWQwYjZlNDJlMDIifQ.ykQeL_Q3vlu8ftUVdxdT-d1hmFKc0zMQ7FGXJixib4Y' },
  authenticated: true } [ { _id: 'f9b6c41d-062f-42fa-9ec9-6f0c161c4204',
    text: 'Test1',
    position: 'left',
    createdAt: '2017-12-12T07:26:56.017Z',
    user: 
     { _id: '5a2f44c39ebbb53e14c6ba40',
       avatar: 'https://raw.githubusercontent.com/feathersjs/feathers-chat/master/public/placeholder.png' } },
  {},
  [Function] ] +6s
  @feathersjs/socket-commons/channels Publishing event created message +7s
  @feathersjs/socket-commons Returned successfully method 'create' on service 'message' { _id: 'f9b6c41d-062f-42fa-9ec9-6f0c161c4204',
  text: 'Test1',
  position: 'left',
  createdAt: '2017-12-12T07:26:56.017Z',
  user: 
   { _id: '5a2f44c39ebbb53e14c6ba40',
     avatar: 'https://raw.githubusercontent.com/feathersjs/feathers-chat/master/public/placeholder.png' } } +9ms
  socket.io:socket sending ack [null,{"_id":"f9b6c41d-062f-42fa-9ec9-6f0c161c4204","text":"Test1","position":"left","createdAt":"2017-12-12T07:26:56.017Z","user":{"_id":"5a2f44c39ebbb53e14c6ba40","avatar":"https://raw.githubusercontent.com/feathersjs/feathers-chat/master/public/placeholder.png"}}] +10ms
  socket.io:client writing packet {"id":3,"type":3,"data":[null,{"_id":"f9b6c41d-062f-42fa-9ec9-6f0c161c4204","text":"Test1","position":"left","createdAt":"2017-12-12T07:26:56.017Z","user":{"_id":"5a2f44c39ebbb53e14c6ba40","avatar":"https://raw.githubusercontent.com/feathersjs/feathers-chat/master/public/placeholder.png"}}],"nsp":"/"} +0ms
  socket.io-parser encoding packet {"id":3,"type":3,"data":[null,{"_id":"f9b6c41d-062f-42fa-9ec9-6f0c161c4204","text":"Test1","position":"left","createdAt":"2017-12-12T07:26:56.017Z","user":{"_id":"5a2f44c39ebbb53e14c6ba40","avatar":"https://raw.githubusercontent.com/feathersjs/feathers-chat/master/public/placeholder.png"}}],"nsp":"/"} +12ms
  socket.io-parser encoded {"id":3,"type":3,"data":[null,{"_id":"f9b6c41d-062f-42fa-9ec9-6f0c161c4204","text":"Test1","position":"left","createdAt":"2017-12-12T07:26:56.017Z","user":{"_id":"5a2f44c39ebbb53e14c6ba40","avatar":"https://raw.githubusercontent.com/feathersjs/feathers-chat/master/public/placeholder.png"}}],"nsp":"/"} as 33[null,{"_id":"f9b6c41d-062f-42fa-9ec9-6f0c161c4204","text":"Test1","position":"left","createdAt":"2017-12-12T07:26:56.017Z","user":{"_id":"5a2f44c39ebbb53e14c6ba40","avatar":"https://raw.githubusercontent.com/feathersjs/feathers-chat/master/public/placeholder.png"}}] +1ms
  engine:socket sending packet "message" (33[null,{"_id":"f9b6c41d-062f-42fa-9ec9-6f0c161c4204","text":"Test1","position":"left","createdAt":"2017-12-12T07:26:56.017Z","user":{"_id":"5a2f44c39ebbb53e14c6ba40","avatar":"https://raw.githubusercontent.com/feathersjs/feathers-chat/master/public/placeholder.png"}}]) +14ms
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "433[null,{"_id":"f9b6c41d-062f-42fa-9ec9-6f0c161c4204","text":"Test1","position":"left","createdAt":"2017-12-12T07:26:56.017Z","user":{"_id":"5a2f44c39ebbb53e14c6ba40","avatar":"https://raw.githubusercontent.com/feathersjs/feathers-chat/master/public/placeholder.png"}}]" +0ms

**Comment by daffl** [comment]
Did you update `channels.js` so publish to a channel as the commented out code suggests?

**Comment by shauncodal** [comment]
Sorry I am such an idiot:( Worked, of course;)
