### ISSUE TITLE
Can't run the app on a device

### ISSUE THREAD

**Issue by riobijanero** [feathersjs/feathers-react-native-chat#27]
Hi, 
when I run the app on the simulator, it works well but when i run on a device with adjusted API_URL, it doesn't connect.

does anyone know why? do i have to change anything in the client?

**Comment by corymsmith** [comment]
What device are you using? Android or iOS? And what’s the url? Is it localhost?

**Comment by riobijanero** [comment]
I'm using an iPhone.
The URL is not localhost. I'm running it through localtunnel.me so I use the URL it gives me, which works fine on the simulator
