### ISSUE TITLE
v3 update

### ISSUE THREAD

**Issue by CyberCyclone** [feathersjs/feathers-react-native-chat#28]
There's a lot of breaking changes to this and the repo itself is based on 3 year old code. It would be great for those starting out to be able to see an example with relatively up to date code.

**Comment by daffl** [comment]
Nothing in the Feathers client usage has changed. If there are breaking changes in React Native, anybody who is familiar with those is welcome to put in a PR.

**Comment by CyberCyclone** [comment]
It's more that the documentation doesn't seem to line up well with this and the migration guide seems to have a lot of differences between V2 and V3.
