### ISSUE TITLE
Created event for a message does not include the populated user in sentBy

### ISSUE THREAD

**Issue by ghost** [feathersjs/feathers-react-native-chat#6]
The sendMessage promise give me the results with the users data inside sendBy while the on created service is missing it.

Something with the hooks I guess ?

**Comment by ekryski** [comment]
@naptiv yup it's an issue in Feathers core and hooks https://github.com/feathersjs/feathers/issues/248. @daffl thinks he has a fix for it.

**Comment by ekryski** [comment]
This was fixed by https://github.com/feathersjs/feathers-hooks/pull/57. I've pushed a new server version and client code so this is now fixed.
