### ISSUE TITLE
Replace react-native-gifted-messenger with our own chat component

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-react-native-chat#8]
Gifted messenger is buggy and the way it handles updating messages is not performant and causes weird flicker issues. It is also causing a bug with loading more data.

**Comment by philohelp** [comment]
That would be a great way to discover feathers :)

**Comment by corymsmith** [comment]
I've updated to the latest `react-native-gifted-chat` and it seems to be working great.
