### ISSUE TITLE
Chat list doesn't show online users

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-react-native-chat#9]
It is actually coded up and does work but marking users as online and offline doesn't happen automatically on the server side. If you change a user to `online: true` then they will appear in the list.

It can be closed when https://github.com/feathersjs/feathers-chat/issues/5 is closed.

**Comment by 29er** [comment]
Is this fixed yet ? I am still unable to see online users in the Drawer.

**Comment by ekryski** [comment]
@29er nope! If it was fixed we'd have closed it. 😉  The core team is busy with more important things right now. Realistically we probably won't get to doing updates on this until the new socket.io release goes out because it has a fix for the `window.navigator` hack (#11).

However, if you want to take a crack at it, then a PR to the https://github.com/feathersjs/feathers-chat repo would be very welcome. That's the root of the issue. The client will show online users if you manually set them to online in your db.

**Comment by 29er** [comment]
@ekryski Thanks! . yea my bad, I saw the 'Closed' but realized that was pertaining to something else. Love what you guys are doing with feathers BTW, I just discovered your library while searching for an alternative to  Meteor : )   keep up the good work !

**Comment by corymsmith** [comment]
Going to close this one for now since its referring to the old app.
